version: "3.8"

services:
  {{ project_slug }}-api:
    build: .
    container_name: {{ project_slug }}-api
    volumes:
      - .:/code
    working_dir: /code 
    ports:
      - "{{ api_port }}:{{ api_port }}"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:{{ postgres_version }}
    container_name: {{ project_slug }}-db
    restart: always
    environment:
      POSTGRES_USER: {{ db_user }}
      POSTGRES_PASSWORD: {{ db_password }}
      POSTGRES_DB: {{ db_name }}
    ports:
      - "{{ db_port }}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
