"""Add price to database

Revision ID: b26a56a0338a
Revises: d2548180ecff
Create Date: 2025-07-09 02:22:08.470810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b26a56a0338a"
down_revision: Union[str, Sequence[str], None] = "d2548180ecff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modality", sa.Column("price", sa.Numeric(precision=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modality", "price")
    # ### end Alembic commands ###
