"""Fix price field

Revision ID: bd90a914e1ad
Revises: b26a56a0338a
Create Date: 2025-07-09 02:53:53.930777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd90a914e1ad"
down_revision: Union[str, Sequence[str], None] = "b26a56a0338a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "modality",
        "price",
        existing_type=sa.NUMERIC(precision=2, scale=0),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "modality",
        "price",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.NUMERIC(precision=2, scale=0),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
